#!/usr/bin/env php
<?php

/** Carrega o autoload do composer */
require __DIR__.'/vendor/autoload.php';

/** Carrega o bootstrap */
require __DIR__.'/bootstrap.php';

require __DIR__.'/scadaunity/Console/helper.php';

if (!isset($argv[1])) {
    $argv[1] = 'list';
    require __DIR__.'/scadaunity/Console/commands/list.php';
    die();
}


require __DIR__.'/scadaunity/Console/commands/routes.php';
require __DIR__.'/scadaunity/Console/commands/list.php';
require __DIR__.'/scadaunity/Console/commands/middleware.php';
require __DIR__.'/scadaunity/Console/commands/controller.php';
require __DIR__.'/scadaunity/Console/commands/serve.php';
require __DIR__.'/scadaunity/Console/commands/migration.php';
require __DIR__.'/scadaunity/Console/commands/compile.php';