#!/usr/bin/env php
<?php

/** Carrega o autoload do composer */
require __DIR__.'/vendor/autoload.php';

/** Carrega o autoload do composer */
require __DIR__.'/ScadaUnity/bootstrap.php';


echo "Bem vindo ao assitente do scada unity framework". PHP_EOL;

/** Carrega o autoload do composer */
require __DIR__.'/ScadaUnity/Console/commands/routes.php';
require __DIR__.'/ScadaUnity/Console/commands/list.php';
require __DIR__.'/ScadaUnity/Console/commands/middleware.php';
